import { Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { apiClient } from "../api/client";
import { ModalOverlay } from "../components/modals/ModalOverlay";
import { Spinner } from "../components/shared/Spinner";
import { StatusBadge } from "../components/shared/StatusBadge";
import type { ReportSummaryDto as ReportSummary } from "../types";
import { OPERATION_LABELS } from "../types";

/**
 * ReportsPage — /reports
 *
 * Displays the history of all reports generated by the user's tasks.
 * Each row links to /reports/:id for the full detail view.
 *
 * The list is fetched once on mount from GET /reports.
 * Reports are sorted by generation date descending (newest first).
 */
export function ReportsPage() {
  const navigate = useNavigate();
  const [reports, setReports] = useState<ReportSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [deleting_id, setDeletingId] = useState<string | null>(null);
  const [report_to_delete, setReportToDelete] = useState<ReportSummary | null>(null);
  const [delete_error, setDeleteError] = useState("");

  useEffect(() => {
    async function fetch_reports() {
      try {
        // GET /reports returns a raw array (ReportSummaryDto[]).
        const response = await apiClient.get<ReportSummary[]>("/reports");
        // Sort newest first.
        const sorted = [...response.data].sort(
          (a, b) => new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime(),
        );
        setReports(sorted);
      } catch {
        setError("Unable to load reports. Try again later.");
      } finally {
        setLoading(false);
      }
    }
    fetch_reports();
  }, []);

  async function handle_delete() {
    if (!report_to_delete) return;
    const report = report_to_delete;
    setDeletingId(report.id);
    setDeleteError("");
    try {
      await apiClient.delete(`/reports/${report.id}`);

      setReports((current) => current.filter(({ id }) => id !== report.id));
      setReportToDelete(null);
    } catch {
      setDeleteError("Unable to delete the report. Try again later.");
    } finally {
      setDeletingId(null);
    }
  }

  function open_report(reportId: string) {
    navigate({ to: "/reports/$id", params: { id: reportId } });
  }

  // ---- Render ----

  if (loading) {
    return (
      <div className="flex items-center gap-2 text-sm text-gray-500">
        <Spinner size="sm" />
        Loading reports…
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl">
      <h1 className="mb-1 text-lg font-semibold text-[#2a2a2a]">Report History</h1>
      <p className="mb-6 text-sm text-gray-400">
        All reports generated by completed operations.
      </p>

      {error && (
        <div className="mb-4 rounded border border-red-200 bg-red-50 px-3 py-2 text-sm text-[#cc2222]">
          {error}
        </div>
      )}

      {reports.length === 0 && !error ? (
        <div className="rounded-lg border border-dashed border-[#cccccc] p-10 text-center text-sm text-gray-400">
          No reports available.{" "}
          <Link to="/run" className="text-[#2277cc] hover:underline">
            Start an operation
          </Link>{" "}
          per generarne uno.
        </div>
      ) : (
        <div className="overflow-hidden rounded-lg border border-[#cccccc]">
          <table className="w-full text-sm">
            <thead className="bg-white text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
              <tr>
                <th className="px-4 py-3">Operazione</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Date</th>
                <th className="px-4 py-3">Duration</th>
                <th className="px-4 py-3">
                  <span className="sr-only">Azioni</span>
                </th>
              </tr>
            </t
head>
            <tbody className="divide-y divide-[#eeeeee] bg-white">
              {reports.map((report) => (
                <tr
                  key={report.id}
                  tabIndex={0}
                  onClick={() => open_report(report.id)}
                  onKeyDown={(event) => {
                    if (event.target !== event.currentTarget) return;
                    if (event.key === "Enter" || event.key === " ") {
                      event.preventDefault();
                      open_report(report.id);
                    }
                  }}
                  className="cursor-pointer outline-none hover:bg-gray-50 focus-visible:bg-blue-50 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#2277cc] transition"
                >
                  <td className="px-4 py-3">
                    <p className="font-medium text-[#2a2a2a]">{report.title}</p>
                    <p className="text-xs text-gray-400 mt-0.5">
                      {OPERATION_LABELS[report.operation] ?? report.operation}
                    </p>
                  </td>

                  <td className="px-4 py-3">
                    <StatusBadge status={report.status} />
                  </td>

                  <td className="px-4 py-3 text-gray-500 text-xs">
                    {new Date(report.generatedAt).toLocaleString("en-US", {
                      day: "2-digit",
                      month: "2-digit",
                      year: "numeric",
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                  </td>

                  <td className="px-4 py-3 text-gray-500 text-xs">
                    {report.durationMs != null ? `${(report.durationMs / 1000).toFixed(1)}s` : "—"}
                  </td>

                  <td className="px-4 py-3 text-right">
                    <button
                      type="button"
                      onClick={(event) => {
                        event
.stopPropagation();
                        setDeleteError("");
                        setReportToDelete(report);
                      }}
                      disabled={deleting_id !== null}
                      className="rounded bg-[#cc2222] px-3 py-1.5 text-xs font-medium text-white hover:bg-[#a61b1b] transition disabled:cursor-not-allowed disabled:opacity-50"
                      aria-label={`Elimina ${report.title}`}
                    >
                      {deleting_id === report.id ? "Deleting…" : "Delete"}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <ModalOverlay
        open={report_to_delete !== null}
        title="Delete report"
        onClose={() => {
          if (deleting_id === null) setReportToDelete(null);
        }}
      >
        <p className="mb-3 text-sm text-gray-600">
          Eliminare definitivamente il report “{report_to_delete?.title}”?
        </p>
        <p className="mb-4 text-xs text-gray-500">This action cannot be undone.</p>
        {delete_error && <p className="mb-3 text-xs text-[#cc2222]">{delete_error}</p>}
        <div className="flex justify-end gap-2">
          <button
            type="button"
            onClick={() => setReportToDelete(null)}
            disabled={deleting_id !== null}
            className="rounded border border-[#cccccc] px-4 py-2 text-sm text-[#2a2a2a] hover:bg-gray-50 transition disabled:opacity-50"
          >
            Annulla
          </button>
          <button
            type="button"
            onClick={handle_delete}
            disabled={deleting_id !== null}
            className="rounded bg-[#cc2222] px-4 py-2 text-sm font-medium text-white hover:bg-[#a61b1b] transition disabled:opacity-50"
          >
            {deleting_id ? "Eliminazione…" : "Delete report"}
          </button>
        </div>
      </ModalOverlay>
    </div>
  );

}
