import { Injectable } from '@nestjs/common';
import { UserRole } from '../auth/schemas/user.schema';
import { OperationCode } from '../common/domain-types';
import {
  AgentName,
  AgentRegistryEntry,
  OperationDescriptorDto,
} from './agent-registry.types';

const ENTRIES: AgentRegistryEntry[] = [
  {
    code: 'DOCS_README',
    displayName: 'README generation/update',
    description:
      'Generates or updates the project README and opens a Pull Request with the proposed changes.',
    agent: 'DOCS',
    allowedRoles: ['DEVELOPER'],
    timeoutS: 150,
  },
  {
    code: 'DOCS_INLINE',
    displayName: 'Inline documentation (JSDoc)',
    description:
      'Adds or fixes JSDoc/docstring comments that are missing or out of sync with the code.',
    agent: 'DOCS',
    allowedRoles: ['DEVELOPER'],
    timeoutS: 90,
  },
  {
    code: 'DOCS_API',
    displayName: 'API documentation',
    description:
      'Generates documentation for the endpoints exposed by the project.',
    agent: 'DOCS',
    allowedRoles: ['DEVELOPER'],
    timeoutS: 150,
  },
  {
    code: 'SECURITY_OWASP',
    displayName: 'OWASP Top 10 vulnerability scan',
    description:
      'Analyzes the code for vulnerabilities matching the OWASP Top 10.',
    agent: 'SECURITY',
    allowedRoles: ['SECURITY_AUDITOR'],
    timeoutS: 180,
  },
  {
    code: 'SECURITY_POLICY',
    displayName: 'Policy-as-code compliance check',
    description:
      "Checks the code against the rules declared in the repository's POLICY.md.",
    agent: 'SECURITY',
    allowedRoles: ['SECURITY_AUDITOR'],
    timeoutS: 120,
  },
  {
    code: 'CHANGELOG_TECHNICAL',
    displayName: 'Technical changelog',
    description:
      'Generates a technical changelog from the User Stories/Issues closed in the given Sprint.',
    agent: 'CHANGELOG',
    allowedRoles: ['PROJECT_MANAGER', 'DEVELOPER'],
    timeoutS: 90,
  },
  {
    code: 'CHANGELOG_BUSINESS',
    displayName: 'Business changelog',
    description:
      'Generates a business-facing changelog from the technical changelog of the same Sprint.',
    agent: 'CHANGELOG',
    allowedRoles: ['PROJECT_MANAGER'],
    timeoutS: 120,
  },
];

@Injectable()
export class AgentRegistry {
  getForRole(role: UserRole): OperationDescriptorDto[] {
    return ENTRIES.filter((entry) => entry.allowedRoles.includes(role)).map(
      ({ code, displayName, description, agent }) => ({
        code,
        displayName,
        description,
        agent,
      }),
    );
  }

  // Agent's own execution budget (Tabella 45), seconds. Callers add their
  // own network margin on top — this is not the gateway's HTTP timeout.
  getTimeoutS(code: OperationCode): number {
    return this.entry(code).timeoutS;
  }

  // BE-17: TaskProcessor needs to know whether an operation belongs to the
  // Changelog agent, to decide whether a Task can be missing a sprintId and
  // still be allowed to reach invoke() unpaused.
  getAgent(code: OperationCode): AgentName {
    return this.entry(code).agent;
  }

  // BE-18: the human-readable half of a Report's deterministic title
  // ("<displayName> — owner/repo@branch") — composed by the backend from
  // data it already has, never generated by the model.
  getDisplayName(code: OperationCode): string {
    return this.entry(code).displayName;
  }

  private entry(code: OperationCode): AgentRegistryEntry {
    const entry = ENTRIES.find((e) => e.code === code);
    if (!entry) {
      throw new Error(`Unknown OperationCode: ${code}`);
    }
    return entry;
  }
}
