import { INestApplication, ValidationPipe } from "@nestjs/common";
import { Test, TestingModule } from "@nestjs/testing";
import request from "supertest";
import { App } from "supertest/types";
import { AppModule } from "./../src/app.module";
import { FRANC } from "./../src/contexts/franc.provider";

/**
 * Application startup and minimal public surface.
 *
 * This file contained the test generated by the NestJS scaffolding —
 * `GET /` expecting "Hello World!" — for an AppController that does not
 * exist in this project: it failed on every `test:e2e` run. In its place
 * it verifies what the application actually exposes.
 */
describe("Application startup (e2e)", () => {
  let app: INestApplication<App>;
  let server: App;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    })
      // franc-min is ESM-only and is resolved with a dynamic import() that
      // Jest cannot run (see the comment in franc.provider.ts).
      .overrideProvider(FRANC)
      .useValue(() => "eng")
      .compile();

    app = moduleFixture.createNestApplication();
    app.useGlobalPipes(
      new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true }),
    );
    app.setGlobalPrefix("api/v1");
    await app.init();
    server = app.getHttpServer();
  }, 60_000);

  afterAll(async () => {
    await app?.close();
  });

  it("responds to the health probe without authentication", async () => {
    // This is what Docker probes to know if the process is alive, before
    // any user has ever logged in.
    const response = await request(server).get("/api/v1/auth/health").expect(200);

    expect(response.body).toEqual({ status: "ok" });
  });

  it("exposes routes under the version prefix", async () => {
    // Without the prefix the frontend, which calls /api/v1, would get 404 on everything.
    await request(server).get("/auth/health").expect(404);
  });

  it("rejects a protected route without a token", async () => {
    await request(server).get("/api/v1/credentials").expect(401);
  });

  it("rejects an invalid token", async () => {
    await request(server)
      .get("/api/v1/credentials")
      .set("Authorization", "Bearer not-a-token")
      .expect(401);
  });

  it("validates the request body according to the DTOs", async () => {
    // whitelist + forbidNonWhitelisted: an unknown field is a 400, not a
    // silently dropped field.
    const response = await request(server)
      .post("/api/v1/auth/login")
      .send({ email: "not-an-email", password: "" })
      .expect(400);

    expect(JSON.stringify(response.body)).toContain("email");
  });
});
