import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";
import { E2EEnvironment, startEnvironment } from "./e2e-helpers";

/**
 * TU_27 (RV.16) — the OpenAPI document generated by the backend.
 *
 * It sits among integration tests and not among unit tests, even though it
 * is catalogued TU: `SwaggerModule.createDocument` wants an already-built
 * Nest application, and building AppModule wants MongoDB and Redis. Putting
 * it in `src/**\/*.spec.ts` would have made `npx jest` dependent on Docker
 * for the entire unit suite. The choice is declared rather than hidden.
 *
 * PARTIAL compliance, for two distinct reasons.
 *
 * The first is a project decision: RV.16 asks for validity "according to
 * the OpenAPI 3.0 schema", and validating against the formal schema
 * requires a validator that the project does not have among its
 * dependencies. Here we verify the properties that can be checked without
 * adding one — declared version, `info`, `paths`, every operation with
 * its described responses, every path parameter typed — plus the second
 * half of the requirement, i.e. that every public endpoint *exists* in the
 * document with its own method. This is not a full schema validation and
 * is not passed off as such.
 *
 * The second is an open defect with three faces, one per `it.failing`:
 * no operation declares the schema of its response, no query parameter is
 * documented, and request body schemas are empty shells. The cause is
 * single: in the controllers there is not a single
 * @ApiResponse/@ApiQuery/@ApiProperty decorator, and nest-cli.json does
 * not enable the @nestjs/swagger plugin that would infer them from types.
 * The practical consequence is that a client written reading this document
 * calls GET /reports/{id}/export without `format=pdf` and receives a 400,
 * and does not know which fields to put in the body of POST /auth/register.
 */
describe("TU_27 (RV.16) — backend OpenAPI document", () => {
  let env: E2EEnvironment;
  let document: Record<string, unknown>;

  const HTTP_METHODS = ["get", "post", "put", "patch", "delete"];

  interface Operation {
    parameters?: {
      name: string;
      in: string;
      required?: boolean;
      schema?: unknown;
    }[];
    responses?: Record<string, { description?: string; content?: unknown }>;
    requestBody?: {
      content?: Record<string, { schema?: { $ref?: string } }>;
    };
  }

  /** The operations of the document, as path/method/definition triples. */
  function operations(): { path: string; method: string; op: Operation }[] {
    const paths = document.paths as Record<string, Record<string, Operation>>;
    return Object.entries(paths).flatMap(([path, byMethod]) =>
      Object.entries(byMethod)
        .filter(([method]) => HTTP_METHODS.includes(method))
        .map(([method, op]) => ({ path, method, op })),
    );
  }

  /**
   * The routes that the application actually serves, read from the Express
   * router after initialization.
   *
   * This is the only source that cannot diverge from what runs: a list
   * rewritten here by hand would only say that this file is consistent
   * with itself, and the forgotten endpoint is exactly the case that
   * RV.16 must catch.
   */
  function registeredRoutes(): string[] {
    const express = env.app.getHttpAdapter().getInstance() as unknown as {
      router?: { stack: unknown[] };
      _router?: { stack: unknown[] };
    };
    const router = express.router ?? express._router;
    if (!router?.stack) {
      throw new Error(
        "The Express router is not reachable: TU_27 cannot compare " +
          "registered routes with documented ones.",
      );
    }

    const layers = router.stack as {
      route?: { path: string; methods: Record<string, boolean> };
    }[];

    return layers
      .filter((layer) => layer.route)
      .flatMap((layer) =>
        Object.keys(layer.route!.methods)
          .filter((method) => HTTP_METHODS.includes(method))
          // Express writes :id, OpenAPI writes {id}: same route, two notations.
          .map((method) => `${method} ${layer.route!.path.replace(/:([A-Za-z0-9_]+)/g, "{$1}")}`),
      );
  }

  /** Internal routes, outside the public perimeter of RV.16. */
  function isInternal(route: string): boolean {
    return route.includes("/internal/");
  }

  beforeAll(async () => {
    env = await startEnvironment();
    // The same settings as main.ts: a document built with other parameters
    // would not be the one the backend publishes at /api/docs.
    const config = new DocumentBuilder()
      .setTitle("Code Guardian — Backend MVP")
      .setDescription("Code Guardian backend API")
      .setVersion("0.1")
      .addBearerAuth()
      .build();
    document = SwaggerModule.createDocument(env.app, config) as unknown as Record<
      string,
      unknown
    >;
  }, 60_000);

  afterAll(async () => {
    await env?.close();
  });

  it("declares OpenAPI version 3.0 and the required info", () => {
    expect(document.openapi).toMatch(/^3\.0\.\d+$/);

    const info = document.info as { title?: string; version?: string };
    expect(info?.title?.length).toBeGreaterThan(0);
    expect(info?.version?.length).toBeGreaterThan(0);
    expect(Object.keys(document.paths as object).length).toBeGreaterThan(0);
  });

  it("every operation declares at least one response, and every response has a description", () => {
    // `description` is required on the Response Object in OpenAPI 3.0: it is
    // the part of the schema that can be verified without a validator.
    const withoutResponses = operations()
      .filter(({ op }) => Object.keys(op.responses ?? {}).length === 0)
      .map(({ method, path }) => `${method} ${path}`);
    expect(withoutResponses).toEqual([]);

    const withoutDescription = operations().flatMap(({ path, method, op }) =>
      Object.entries(op.responses ?? {})
        .filter(([, response]) => typeof response.description !== "string")
        .map(([code]) => `${method} ${path} -> ${code}`),
    );
    expect(withoutDescription).toEqual([]);
  });

  it("every path parameter is documented as required and typed", () => {
    const missing = operations().flatMap(({ path, method, op }) => {
      const placeholders = [...path.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]);
      return placeholders
        .filter((name) => {
          const parameter = (op.parameters ?? []).find((p) => p.name === name && p.in === "path");
          return !parameter || parameter.required !== true || !parameter.schema;
        })
        .map((name) => `${method} ${path} -> {${name}}`);
    });

    expect(missing).toEqual([]);
  });

  it("every public endpoint served by the application appears in the document", () => {
    const registered = registeredRoutes().filter((r) => !isInternal(r));
    const documented = operations().map(({ method, path }) => `${method} ${path}`);

    expect(registered.length).toBeGreaterThan(20);
    expect(registered.filter((r) => !documented.includes(r))).toEqual([]);
  });

  it("the document does not promise endpoints the application does not serve", () => {
    // The mirror error, equally harmful for integrators: a route removed
    // from the code but left in the documentation.
    const registered = registeredRoutes();
    const documented = operations().map(({ method, path }) => `${method} ${path}`);

    expect(documented.filter((r) => !registered.includes(r))).toEqual([]);
  });

  it("internal endpoints stay out of the public document", () => {
    // RV.16 concerns public endpoints. Those between backend and agents are
    // excluded with @ApiExcludeController and must not appear: they are
    // protected by HMAC and documenting them would not help any legitimate
    // client.
    const internal = registeredRoutes().filter(isInternal);
    expect(internal.length).toBeGreaterThan(0);

    const documented = operations().map(({ method, path }) => `${method} ${path}`);
    expect(internal.filter((r) => documented.includes(r))).toEqual([]);
  });

  /** The schemas declared in components. */
  function declaredSchemas(): Record<string, { properties?: object }> {
    return (
      document.components as {
        schemas?: Record<string, { properties?: object }>;
      }
    ).schemas!;
  }

  /** The operations that accept a body, with the reference to their schema. */
  function requestBodies(): { label: string; reference?: string }[] {
    return operations()
      .filter(({ op }) => op.requestBody)
      .map(({ path, method, op }) => ({
        label: `${method} ${path}`,
        reference: op.requestBody?.content?.["application/json"]?.schema?.$ref,
      }));
  }

  it("every request body references a schema declared in components", () => {
    const schemas = declaredSchemas();
    const bodies = requestBodies();
    expect(bodies.length).toBeGreaterThanOrEqual(5);

    const unresolved = bodies.filter(({ reference }) => {
      if (!reference) return true;
      return !(reference.replace("#/components/schemas/", "") in schemas);
    });

    expect(unresolved.map((c) => c.label)).toEqual([]);
  });

  it.fails("RV.16 — OPEN DEFECT: request body schemas are empty", () => {
    // Third face of the same defect: without @ApiProperty on DTO fields
    // (and without the plugin), every schema is {type:'object',
    // properties:{}}. The document says what the body of a
    // POST /auth/register is called, not that it wants firstName, lastName,
    // email, password and role.
    const schemas = declaredSchemas();
    const empty = Object.entries(schemas)
      .filter(([, schema]) => Object.keys(schema.properties ?? {}).length === 0)
      .map(([name]) => name);

    expect(empty).toEqual([]);
  });

  it.fails("RV.16 — OPEN DEFECT: no operation documents the schema of its response", () => {
    // Without @ApiResponse (and without the @nestjs/swagger plugin in
    // nest-cli.json), every response is a shell: status code and empty
    // description, no `content`. The integrator does not know what they
    // receive, which is half of what RV.16 asks for.
    const withoutSchema = operations()
      .filter(({ op }) => Object.values(op.responses ?? {}).every((response) => !response.content))
      .map(({ method, path }) => `${method} ${path}`);

    expect(withoutSchema).toEqual([]);
  });

  it("RV.16 — query parameters are documented", () => {
    // The hands-on case: GET /reports/{id}/export accepts an
    // ExportReportQueryDto with required `format`, and the document does
    // not name it. A client written reading the documentation calls the
    // endpoint without that parameter and receives a 400.
    const exportOp = operations().find(
      ({ path, method }) => path.endsWith("/export") && method === "get",
    );
    expect(exportOp).toBeDefined();

    const format = (exportOp!.op.parameters ?? []).find(
      (p) => p.name === "format" && p.in === "query",
    );
    expect(format).toBeDefined();
    expect(format!.required).toBe(true);
  });
});
