"""Shared data contract (Report Envelope).

Exactly reflects the class diagram (Figure 4) of the specifications.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

# --- Shared Types and Enumerations ---

OperationCode = Literal[
    "DOCS_README",
    "DOCS_INLINE",
    "DOCS_API",
    "SECURITY_OWASP",
    "SECURITY_POLICY",
    "CHANGELOG_TECHNICAL",
    "CHANGELOG_BUSINESS",
]

ReportStatus = Literal["COMPLETED", "FAILED"]

Severity = Literal["INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL"]
SEVERITY_ORDER: tuple[str, ...] = ("INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL")


class ErrorKind(StrEnum):
    """Enumeration of possible error kinds."""

    TIMEOUT = "TIMEOUT"
    PARSING = "PARSING"
    UPSTREAM = "UPSTREAM"
    CONTEXT_TOO_LARGE = "CONTEXT_TOO_LARGE"
    CONTEXT_RESOURCE_MISSING = "CONTEXT_RESOURCE_MISSING"
    CONTEXT_RESOURCE_INVALID = "CONTEXT_RESOURCE_INVALID"
    READABILITY_TOO_LOW = "READABILITY_TOO_LOW"
    RATE_LIMITED = "RATE_LIMITED"


class _Immutable(BaseModel):
    """Base class for immutable models."""

    model_config = ConfigDict(frozen=True)


# --- Error and Proposal ---


class ReportError(_Immutable):
    """Represents an error within the report."""

    kind: ErrorKind
    message: str
    stage: str


class Proposal(_Immutable):
    """Represents a proposed change in the repository."""

    targetPath: str
    diffUnified: str
    language: str
    pullRequestUrl: str | None = None


# --- Report Body Blocks (Polymorphism) ---


class TextBlock(_Immutable):
    """Represents a standard text block."""

    kind: Literal["TEXT"] = "TEXT"
    order: int
    markdown: str


class RemediationSnippet(_Immutable):
    """Represents a code snippet for remediation."""

    kind: Literal["SNIPPET"] = "SNIPPET"
    language: str
    code: str


class RemediationText(_Immutable):
    """Represents a textual description for remediation."""

    kind: Literal["TEXT"] = "TEXT"
    text: str


Remediation = Annotated[
    RemediationSnippet | RemediationText, Field(discriminator="kind")
]


class FindingBlock(_Immutable):
    """Represents a security finding block."""

    kind: Literal["FINDING"] = "FINDING"
    order: int
    category: str
    severity: Severity
    filePath: str
    lineStart: int
    lineEnd: int | None = None
    description: str
    remediation: Remediation


class PolicyViolationBlock(_Immutable):
    """Represents a policy violation block."""

    kind: Literal["POLICY_VIOLATION"] = "POLICY_VIOLATION"
    order: int
    ruleId: str
    ruleText: str
    filePath: str
    lineStart: int | None = None
    lineEnd: int | None = None
    severity: Severity
    explanation: str
    remediation: Remediation


class ComplexityWarningBlock(_Immutable):
    """Represents an excessive complexity warning block."""

    kind: Literal["COMPLEXITY_WARNING"] = "COMPLEXITY_WARNING"
    category: Literal["EXCESSIVE_COMPLEXITY"] = "EXCESSIVE_COMPLEXITY"
    order: int
    severity: Literal["INFO"] = "INFO"  # Fixed value, not generated by LLM
    filePath: str
    lineStart: int
    lineEnd: int
    # Name aligned with the shared contract (shared/src/types.ts): was `reason`,
    # but the frontend and the PDF composer read `explanation` on this block
    # exactly as on PolicyViolationBlock.
    explanation: str


class ChangelogItemBlock(_Immutable):
    """Represents a changelog item block."""

    kind: Literal["CHANGELOG_ITEM"] = "CHANGELOG_ITEM"
    order: int
    issueRef: str
    title: str
    detail: str


# --- SAST Blocks (Semgrep integration) ---

SastVerdict = Literal["CONFIRMED", "FALSE_POSITIVE", "NEEDS_REVIEW"]
SastRuleSeverity = Literal["ERROR", "WARNING", "INFO"]

# Semgrep has its own severity vocabulary (three levels) different from the
# report's (five). Both are kept: `severity` to make the frontend filter
# and badge work as on every other block, `ruleSeverity` to still be able
# to compare the report with a raw Semgrep scan.
SEMGREP_SEVERITY_MAP: dict[str, Severity] = {
    "ERROR": "HIGH",
    "WARNING": "MEDIUM",
    "INFO": "INFO",
}


class SastFindingBlock(BaseModel):
    """A finding raised by static analysis (Semgrep).

    Not `_Immutable` like the other blocks on purpose: `verdict` and
    `llmRemediation` are assigned *after* construction, when the LLM
    has judged the finding (OwaspScanProfile.parse_output).
    """

    kind: Literal["SAST_FINDING"] = "SAST_FINDING"
    order: int = 0
    ruleId: str
    owaspCategory: str
    cwe: str | None = None
    severity: Severity
    ruleSeverity: SastRuleSeverity
    filePath: str
    lineStart: int
    message: str
    codeSnippet: str | None = None
    verdict: SastVerdict = "NEEDS_REVIEW"
    llmRemediation: str | None = None


class SastSummaryBlock(BaseModel):
    """Aggregated summary of the SAST phase."""

    kind: Literal["SAST_SUMMARY"] = "SAST_SUMMARY"
    order: int = 0
    totalFindings: int
    confirmedFindings: int = 0
    falsePositives: int = 0
    needsReview: int = 0
    cappedFindings: int = 0
    scannedFiles: int = 0
    durationMs: int = 0
    timedOut: bool = False


Block = Annotated[
    TextBlock
    | FindingBlock
    | PolicyViolationBlock
    | ComplexityWarningBlock
    | ChangelogItemBlock
    | SastFindingBlock
    | SastSummaryBlock,
    Field(discriminator="kind"),
]


class ReportContext(BaseModel):
    """Denormalized snapshot of the context at the time of the Report."""

    repoOwner: str
    repoName: str
    repoUrl: str
    branch: str
    resolvedSha: str
    scopeType: str
    paths: list[str] = Field(default_factory=list)


class PendingAction(BaseModel):
    """Read-only projection of Task.pendingInput for the frontend."""

    kind: Literal["BUSINESS_CONFIRMATION"]
    taskId: str
    actions: list[Literal["PROCEED", "CANCEL"]]


# --- Main Envelope ---


class Report(BaseModel):
    """The main envelope representing the output report."""

    id: str | None = None
    taskId: str
    agentId: str
    operation: OperationCode
    status: ReportStatus = "COMPLETED"
    # NOTE: According to MVP specs, the title is composed deterministically
    # by the NestJS backend. The agent defaults this to an empty string.
    title: str = ""
    summary: str | None = None
    generatedAt: datetime = Field(default_factory=lambda: datetime.now(UTC))
    executionTimeMs: int | None = None
    tokensConsumed: int = 0
    context: ReportContext
    error: ReportError | None = None
    body: list[Block] = Field(default_factory=list)
    proposal: Proposal | None = None
    pendingAction: PendingAction | None = None

    def to_dict(self) -> dict:
        """Serializes the report to a dictionary.

        Returns:
            dict: The serialized report.
        """
        return self.model_dump(mode="json")

    def to_json(self, indent: int = 2) -> str:
        """Serializes the report to a JSON string.

        Args:
            indent (int, optional): Indentation level. Defaults to 2.

        Returns:
            str: The JSON string representation of the report.
        """
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)


# --- Pause/Resume Mechanism Payloads ---


class PendingInputSprintId(BaseModel):
    """Pending input for the Sprint ID request."""

    kind: Literal["SPRINT_ID"]


class PendingInputIncompleteTasks(BaseModel):
    """Pending input for excluding tasks with insufficient metadata."""

    kind: Literal["INCOMPLETE_TASKS"]
    taskIds: list[str]


class PendingInputBusinessConfirmation(BaseModel):
    """Pending input for the business changelog confirmation."""

    kind: Literal["BUSINESS_CONFIRMATION"]
    # The technical changelog just produced, as Markdown text.
    #
    # This used to be `technicalReportId`, with a note that NestJS would
    # fill it after persisting the report. That could not happen: at that
    # point the technical Report does not exist yet, because the two
    # phases live inside a single Task and the Report is born at the end.
    # The text is sent instead, which is already available.
    technicalChangelog: str = ""
    # True when the text was truncated at the cap: the interface needs this
    # to say so, rather than letting it appear that the changelog ends there.
    technicalChangelogTruncated: bool = False


PendingInput = Annotated[
    PendingInputSprintId
    | PendingInputIncompleteTasks
    | PendingInputBusinessConfirmation,
    Field(discriminator="kind"),
]


class AgentStepResult(BaseModel):
    """Represents the result of an agent step execution."""

    status: Literal["interrupted", "completed", "failed"]
    pendingInput: PendingInput | None = None
    # Run payload for the backend (AgentRunPayload): body, proposal, summary,
    # tokensConsumed. NOT the full Report: title, context and status are
    # composed by the backend, which is the only one that knows them reliably.
    result: dict | None = None
    # Human-readable failure message.
    error: str | None = None
    # Failure classification (ErrorKind on the Python side). Separate from
    # `error` because the backend maps it to its own error.code catalog:
    # passing it the message instead of the category sent every failure to
    # UPSTREAM.
    errorKind: str | None = None


class StartAgentRequest(BaseModel):
    """Represents a request to start an agent."""

    taskId: str
    threadId: str
    operationCode: str
    payload: dict


class ResumeAgentRequest(BaseModel):
    """Represents a request to resume an agent."""

    taskId: str
    threadId: str
    operationCode: str
    inputValue: Any
    # Optional: on a resume the agent state (toolset included) is
    # restored from the LangGraph checkpoint, so the backend has no reason
    # to resend it. Required as it was, it caused every resume to fail with 422.

    userId: str | None = None
