name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read # In questo caso basta read perché non facciamo push sulla repo
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # STEP 1: Prepariamo la cartella del sito copiando i documenti
      - name: Includi Documentazione nel sito
        run: |
          mkdir -p ./Website/Documentazione
          cp -r ./Documentazione/. ./Website/Documentazione/

      # STEP 2: Generiamo l'index leggendo i file appena copiati
      - name: Genera Index HTML
        run: python Website/generate_index.py

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # STEP 3: Carichiamo la cartella Website (che ora contiene tutto)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Website'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4