import * as cdk from "aws-cdk-lib";
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";
import * as origins from "aws-cdk-lib/aws-cloudfront-origins";
import type * as elbv2 from "aws-cdk-lib/aws-elasticloadbalancingv2";
import * as iam from "aws-cdk-lib/aws-iam";
import * as s3 from "aws-cdk-lib/aws-s3";
import type { Construct } from "constructs";

export interface CloudFrontStackProps extends cdk.StackProps {
  alb: elbv2.IApplicationLoadBalancer;
  ciRole: iam.IRole;
}

// Static frontend bucket + CloudFront distribution with Origin Access
// Control. The bucket is created HERE, not in storage-stack.ts: the
// `S3BucketOrigin.withOriginAccessControl()` shortcut attaches the bucket
// policy with the distribution ARN by itself while building the origin,
// i.e. before the distribution exists -- if bucket and distribution live
// in different stacks this creates a known circular dependency
// (aws/aws-cdk#31462). Same stack, problem eliminated at the root.
export class CloudFrontStack extends cdk.Stack {
  public readonly frontendBucket: s3.Bucket;
  public readonly distribution: cloudfront.Distribution;

  constructor(scope: Construct, id: string, props: CloudFrontStackProps) {
    super(scope, id, props);
    const { alb, ciRole } = props;

    // No native static hosting: SPA routing (403/404 -> index.html) is
    // handled by CloudFront (errorResponses below).
    this.frontendBucket = new s3.Bucket(this, "FrontendBucket", {
      bucketName: undefined, // name generated by CloudFormation, avoids global collisions
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      versioned: false,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    const s3Origin = origins.S3BucketOrigin.withOriginAccessControl(this.frontendBucket);

    // Origin in HTTP: the ALB has no TLS certificate, the viewer still
    // speaks HTTPS with CloudFront.
    const albOrigin = new origins.HttpOrigin(alb.loadBalancerDnsName, {
      protocolPolicy: cloudfront.OriginProtocolPolicy.HTTP_ONLY,
    });

    const apiBehavior: cloudfront.BehaviorOptions = {
      origin: albOrigin,
      viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
      cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
      originRequestPolicy: cloudfront.OriginRequestPolicy.ALL_VIEWER,
      allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
    };

    this.distribution = new cloudfront.Distribution(this, "Distribution", {
      comment: "Code Guardian MVP -- shared Frontend + API + WebSocket distribution",
      defaultBehavior: {
        origin: s3Origin,
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
      },
      additionalBehaviors: {
        "/api/*": apiBehavior,
        "/socket.io/*": apiBehavior,
      },
      // SPA routing: the 403/404 errors generated by S3 (private bucket)
      // must be redirected to index.html with status 200, otherwise the
      // client-side router does not work on a page refresh.
      errorResponses: [
        {
          httpStatus: 403,
          responseHttpStatus: 200,
          responsePagePath: "/index.html",
          ttl: cdk.Duration.seconds(0),
        },
        {
          httpStatus: 404,
          responseHttpStatus: 200,
          responsePagePath: "/index.html",
          ttl: cdk.Duration.seconds(0),
        },
      ],
      defaultRootObject: "index.html",
      priceClass: cloudfront.PriceClass.PRICE_CLASS_100,
    });

    // Cache invalidation and bucket sync permissions for the CI/CD pipeline.
    ciRole.attachInlinePolicy(
      new iam.Policy(this, "CiInvalidationPolicy", {
        statements: [
          new iam.PolicyStatement({
            sid: "CloudFrontInvalidate",
            actions: ["cloudfront:CreateInvalidation"],
            resources: [this.distribution.distributionArn],
          }),
          new iam.PolicyStatement({
            sid: "SyncFrontendBucket",
            actions: ["s3:PutObject", "s3:DeleteObject", "s3:ListBucket"],
            resources: [this.frontendBucket.bucketArn, this.frontendBucket.arnForObjects("*")],
          }),
        ],
      }),
    );

    new cdk.CfnOutput(this, "FrontendBucketName", { value: this.frontendBucket.bucketName });
    new cdk.CfnOutput(this, "DistributionDomainName", {
      value: this.distribution.distributionDomainName,
    });
    new cdk.CfnOutput(this, "DistributionId", { value: this.distribution.distributionId });
  }
}
