import * as cdk from "aws-cdk-lib";
import * as cloudwatch from "aws-cdk-lib/aws-cloudwatch";
import { SnsAction } from "aws-cdk-lib/aws-cloudwatch-actions";
import type * as ecs from "aws-cdk-lib/aws-ecs";
import type * as elasticache from "aws-cdk-lib/aws-elasticache";
import * as elbv2 from "aws-cdk-lib/aws-elasticloadbalancingv2";
import * as iam from "aws-cdk-lib/aws-iam";
import * as sns from "aws-cdk-lib/aws-sns";
import * as subscriptions from "aws-cdk-lib/aws-sns-subscriptions";
import type { Construct } from "constructs";
import { SNS_ALERTS_TOPIC_NAME } from "./config";

export interface ObservabilityStackProps extends cdk.StackProps {
  cluster: ecs.ICluster;
  backendService: ecs.FargateService;
  agentsService: ecs.FargateService;
  backendTargetGroup: elbv2.ApplicationTargetGroup;
  redis: elasticache.CfnReplicationGroup;
  alertEmail: string;
}

// SNS Topic and CloudWatch alarms. Log Group and Container Insights are in
// compute-stack.ts (they are properties of Task Definition and Cluster).
// The actual Budget resource is in budget-stack.ts, see below for why.
//
// MongoDB Atlas cluster metrics do not arrive on CloudWatch: alerting for
// those is configured on the Atlas side (console -> Alerts).
export class ObservabilityStack extends cdk.Stack {
  public readonly alertsTopic: sns.Topic;

  constructor(scope: Construct, id: string, props: ObservabilityStackProps) {
    super(scope, id, props);
    const { cluster, backendService, agentsService, backendTargetGroup, redis, alertEmail } = props;

    this.alertsTopic = new sns.Topic(this, "AlertsTopic", {
      topicName: SNS_ALERTS_TOPIC_NAME,
      displayName: "Code Guardian -- MVP infrastructure alarms",
    });
    this.alertsTopic.addSubscription(new subscriptions.EmailSubscription(alertEmail));
    // Requires a confirmation click in the received email -- verify the
    // "Confirmed" status in the SNS console, otherwise alarms never arrive.

    const alarmAction = new SnsAction(this.alertsTopic);
    const fiveMinutes = cdk.Duration.minutes(5);

    for (const [name, service] of [
      ["Backend", backendService],
      ["Agents", agentsService],
    ] as const) {
      new cloudwatch.Alarm(this, `${name}RunningTaskCountAlarm`, {
        alarmName: `codeguardian-${name.toLowerCase()}-running-tasks-below-desired`,
        alarmDescription: `Running tasks < 1 (Desired Count) for ${name} service for > 5 minutes`,
        metric: new cloudwatch.Metric({
          namespace: "ECS/ContainerInsights",
          metricName: "RunningTaskCount",
          dimensionsMap: { ClusterName: cluster.clusterName, ServiceName: service.serviceName },
          statistic: "Minimum",
          period: fiveMinutes,
        }),
        threshold: 1,
        comparisonOperator: cloudwatch.ComparisonOperator.LESS_THAN_THRESHOLD,
        evaluationPeriods: 1,
        treatMissingData: cloudwatch.TreatMissingData.BREACHING,
      }).addAlarmAction(alarmAction);

      new cloudwatch.Alarm(this, `${name}CpuAlarm`, {
        alarmName: `codeguardian-${name.toLowerCase()}-cpu-high`,
        alarmDescription: `CPU utilization for ${name} service > 80% for > 5 minutes`,
        metric: service.metricCpuUtilization({ period: fiveMinutes }),
        threshold: 80,
        comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
        evaluationPeriods: 1,
        treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
      }).addAlarmAction(alarmAction);

      new cloudwatch.Alarm(this, `${name}MemoryAlarm`, {
        alarmName: `codeguardian-${name.toLowerCase()}-memory-high`,
        alarmDescription: `Memory utilization for ${name} service > 80% for > 5 minutes`,
        metric: service.metricMemoryUtilization({ period: fiveMinutes }),
        threshold: 80,
        comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
        evaluationPeriods: 1,
        treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
      }).addAlarmAction(alarmAction);
    }

    // 5xx error rate on the target group (not the ELB), to isolate errors
    // generated by the backend from those generated at the edge.
    const target5xx = backendTargetGroup.metrics.httpCodeTarget(
      elbv2.HttpCodeTarget.TARGET_5XX_COUNT,
      {
        statistic: "Sum",
        period: fiveMinutes,
      },
    );
    const requestCount = backendTargetGroup.metrics.requestCount({
      statistic: "Sum",
      period: fiveMinutes,
    });
    const errorRate = new cloudwatch.MathExpression({
      expression: "(errors / requests) * 100",
      usingMetrics: { errors: target5xx, requests: requestCount },
      period: fiveMinutes,
      label: "5xx error rate (%)",
    });
    new cloudwatch.Alarm(this, "Alb5xxErrorRateAlarm", {
      alarmName: "codeguardian-alb-5xx-rate-high",
      alarmDescription: "HTTP 5xx error rate > 5% over a 5-minute window",
      metric: errorRate,
      threshold: 5,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      evaluationPeriods: 1,
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    }).addAlarmAction(alarmAction);

    // For a single-node Replication Group, AWS automatically assigns the
    // CacheClusterId `<replicationGroupId>-001`.
    const redisCacheClusterId = cdk.Fn.join("", [redis.ref, "-001"]);
    new cloudwatch.Alarm(this, "RedisCpuAlarm", {
      alarmName: "codeguardian-redis-cpu-high",
      alarmDescription: "ElastiCache Redis CPU utilization > 80% for > 5 minutes",
      metric: new cloudwatch.Metric({
        namespace: "AWS/ElastiCache",
        metricName: "EngineCPUUtilization",
        dimensionsMap: { CacheClusterId: redisCacheClusterId },
        statistic: "Average",
        period: fiveMinutes,
      }),
      threshold: 80,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      evaluationPeriods: 1,
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    }).addAlarmAction(alarmAction);

    new cloudwatch.Alarm(this, "BedrockThrottleAlarm", {
      alarmName: "codeguardian-bedrock-invocation-throttling",
      alarmDescription: ">= 1 Bedrock invocation throttled in 5 minutes",
      metric: new cloudwatch.Metric({
        namespace: "AWS/Bedrock",
        metricName: "InvocationThrottles",
        statistic: "Sum",
        period: fiveMinutes,
      }),
      threshold: 1,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
      evaluationPeriods: 1,
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    }).addAlarmAction(alarmAction);

    // AWS::Budgets::Budget exists only in us-east-1 (global service): it
    // lives separately in budget-stack.ts and publishes to this topic's
    // ARN. Here it is enough to grant publish permission.
    this.alertsTopic.grantPublish(new iam.ServicePrincipal("budgets.amazonaws.com"));

    new cdk.CfnOutput(this, "AlertsTopicArn", { value: this.alertsTopic.topicArn });
  }
}
