import * as cdk from "aws-cdk-lib";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as iam from "aws-cdk-lib/aws-iam";
import * as s3 from "aws-cdk-lib/aws-s3";
import type { Construct } from "constructs";

export interface VpcEndpointsStackProps extends cdk.StackProps {
  vpc: ec2.IVpc;
  sgVpce: ec2.ISecurityGroup; // generic Interface endpoints (SM, ECR, CloudWatch, SSM)
  sgBedrock: ec2.ISecurityGroup; // Bedrock Runtime endpoint, ingress only from sg-agents
  artifactsBucket: s3.IBucket;
}

// VPC Endpoints: all traffic towards AWS services stays inside the VPC
// from here (tasks are in private subnets without public IP). The NAT is
// only for outbound traffic to GitHub. The endpoint towards MongoDB Atlas
// is not here: its `serviceName` is generated by Atlas, it is not a
// "com.amazonaws.*" service like the others, so it lives in atlas-stack.ts.
//
// The `new ec2.GatewayVpcEndpoint`/`InterfaceVpcEndpoint` constructors are
// used instead of the `vpc.addGatewayEndpoint()`/`addInterfaceEndpoint()`
// shortcuts: those create the endpoint as a child of `vpc`, i.e. inside
// Network, not here. Passing sgVpce/sgBedrock (from SecurityGroups) would
// result in Network -> SecurityGroups, while SecurityGroups already
// depends on Network for the VPC: a cycle. By instantiating here on `this`,
// the dependency stays one-directional.
export class VpcEndpointsStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: VpcEndpointsStackProps) {
    super(scope, id, props);
    const { vpc, sgVpce, sgBedrock, artifactsBucket } = props;

    const privateSubnets = { subnets: vpc.privateSubnets };

    // Gateway Endpoint: acts on the route table, no Private DNS or SG.
    const s3Endpoint = new ec2.GatewayVpcEndpoint(this, "S3Endpoint", {
      vpc,
      service: ec2.GatewayVpcEndpointAwsService.S3,
      subnets: [privateSubnets],
    });

    // The artifacts bucket is reachable only from here: deny object
    // operations if they do not come from this endpoint. Intentionally
    // does not cover control-plane actions (PutBucketPolicy etc.), which
    // go through the CloudFormation control plane, not through a VPC
    // Endpoint -- otherwise a future deploy touching the bucket would
    // block itself.
    //
    // Built by hand as `s3.BucketPolicy` (not with
    // `artifactsBucket.addToResourcePolicy`, which would create it in
    // storage-stack.ts referencing `s3Endpoint` from here -- same cycle as
    // before, via S3 instead of EC2). Also includes the HTTPS-only
    // constraint that would normally come from `enforceSSL: true` on the
    // bucket, omitted in storage-stack.ts for the same reason.
    new s3.BucketPolicy(this, "ArtifactsBucketPolicy", {
      bucket: artifactsBucket,
      document: new iam.PolicyDocument({
        statements: [
          new iam.PolicyStatement({
            sid: "RestrictObjectAccessToS3GatewayEndpoint",
            effect: iam.Effect.DENY,
            principals: [new iam.AnyPrincipal()],
            actions: ["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:ListBucket"],
            resources: [artifactsBucket.bucketArn, artifactsBucket.arnForObjects("*")],
            conditions: {
              StringNotEquals: { "aws:SourceVpce": s3Endpoint.vpcEndpointId },
            },
          }),
          new iam.PolicyStatement({
            sid: "DenyInsecureTransport",
            effect: iam.Effect.DENY,
            principals: [new iam.AnyPrincipal()],
            actions: ["s3:*"],
            resources: [artifactsBucket.bucketArn, artifactsBucket.arnForObjects("*")],
            conditions: {
              Bool: { "aws:SecureTransport": "false" },
            },
          }),
        ],
      }),
    });

    // Bedrock Runtime on a dedicated SG: only agents reach it.
    new ec2.InterfaceVpcEndpoint(this, "BedrockRuntimeEndpoint", {
      vpc,
      service: ec2.InterfaceVpcEndpointAwsService.BEDROCK_RUNTIME,
      subnets: privateSubnets,
      securityGroups: [sgBedrock],
      privateDnsEnabled: true,
    });

    // "Generic" endpoints, shared between backend and agents: Secrets
    // Manager, ECR (api + dkr), CloudWatch Logs, SSM/SSM Messages/EC2
    // Messages.
    const genericInterfaceEndpoints: Array<[string, ec2.InterfaceVpcEndpointAwsService]> = [
      ["SecretsManagerEndpoint", ec2.InterfaceVpcEndpointAwsService.SECRETS_MANAGER],
      ["EcrApiEndpoint", ec2.InterfaceVpcEndpointAwsService.ECR],
      ["EcrDkrEndpoint", ec2.InterfaceVpcEndpointAwsService.ECR_DOCKER],
      ["CloudWatchLogsEndpoint", ec2.InterfaceVpcEndpointAwsService.CLOUDWATCH_LOGS],
      ["SsmEndpoint", ec2.InterfaceVpcEndpointAwsService.SSM],
      ["SsmMessagesEndpoint", ec2.InterfaceVpcEndpointAwsService.SSM_MESSAGES],
      ["Ec2MessagesEndpoint", ec2.InterfaceVpcEndpointAwsService.EC2_MESSAGES],
    ];

    for (const [id2, service] of genericInterfaceEndpoints) {
      new ec2.InterfaceVpcEndpoint(this, id2, {
        vpc,
        service,
        subnets: privateSubnets,
        securityGroups: [sgVpce],
        privateDnsEnabled: true,
      });
    }

    // 8 Interface Endpoints across 2 AZs = 16 ENIs billed continuously
    // (plus Atlas PrivateLink separately): keep this in mind for the cost
    // estimate.
  }
}
